# Generated by Django 4.2.7 on 2023-12-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_question_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
    ]
