# Generated by Django 4.2.7 on 2023-12-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_title_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
